import "./globals.css";

export const metadata = {
  title: "App Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div className="min-h-screen text-2xl text-black">{children}</div>
      </body>
    </html>
  );
}
